; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35728.0 

	TITLE	C:\Users\24130\Desktop\C++\Project1\Project1\Debug\Math.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	__Avx2WmemEnabledWeakValue
;	COMDAT __Avx2WmemEnabledWeakValue
_BSS	SEGMENT
__Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__7894706E_concurrencysal@h DB 01H
__25A6D1C6_sal@h DB 01H
__4722BC79_vadefs@h DB 01H
__9431CA1C_vcruntime@h DB 01H
__70EC8F01_xkeycheck@h DB 01H
__D04E61C8_yvals_core@h DB 01H
__C1969824_corecrt@h DB 01H
__3F006935_float@h DB 01H
__3426F644_cfloat DB 01H
__8159FC20_limits@h DB 01H
__75E8B6DC_climits DB 01H
__EDDE1938_vcruntime_new@h DB 01H
__A7EED199_vcruntime_new_debug@h DB 01H
__670FEF70_crtdbg@h DB 01H
__3036F4CE_crtdefs@h DB 01H
__602C6FC9_use_ansi@h DB 01H
__47472291_yvals@h DB 01H
__33BD3B06_corecrt_math@h DB 01H
__701A66D6_math@h DB 01H
__9AC76BD6_corecrt_malloc@h DB 01H
__E7A7BB74_stddef@h DB 01H
__227406B8_corecrt_search@h DB 01H
__64EFF10E_corecrt_wstdlib@h DB 01H
__9A08E7D1_stdlib@h DB 01H
__F107942E_cstdlib DB 01H
__9B225D80_xtr1common DB 01H
__3D6F28D3_intrin0@inl@h DB 01H
__291B4DC5_intrin0@h DB 01H
__54CC4E83_cstddef DB 01H
__3F2FD21F_stdint@h DB 01H
__4C597553_cstdint DB 01H
__3E4549CA_type_traits DB 01H
__471CDF71_cmath DB 01H
__9AAF47B7_corecrt_stdio_config@h DB 01H
__7479A65D_corecrt_wstdio@h DB 01H
__47740FC5_stdio@h DB 01H
__47623DC3_cstdio DB 01H
__E7541FB7_errno@h DB 01H
__6C87265B_vcruntime_string@h DB 01H
__394235B6_corecrt_memcpy_s@h DB 01H
__51B64F54_corecrt_memory@h DB 01H
__E29C65AA_corecrt_wstring@h DB 01H
__1C7B7375_string@h DB 01H
__BD953CCE_cstring DB 01H
__3006D06A_corecrt_wconio@h DB 01H
__AB51F463_corecrt_wctype@h DB 01H
__BB118863_corecrt_wdirect@h DB 01H
__F79F6294_corecrt_share@h DB 01H
__782D047E_corecrt_wio@h DB 01H
__4714706A_corecrt_wprocess@h DB 01H
__4FCE886F_corecrt_wtime@h DB 01H
__2FB5D59F_types@h DB 01H
__5AD7D25C_stat@h DB 01H
__AF4C3A1C_setjmp@h DB 01H
__A50CC44A_mmintrin@h DB 01H
__0E25C027_malloc@h DB 01H
__14E4A648_xmmintrin@h DB 01H
__71862F84_emmintrin@h DB 01H
__AE27470D_pmmintrin@h DB 01H
__1EFE348F_tmmintrin@h DB 01H
__37C5210C_smmintrin@h DB 01H
__52A7A8C0_nmmintrin@h DB 01H
__871C528E_wmmintrin@h DB 01H
__4C881F89_zmmintrin@h DB 01H
__7B9CBD43_immintrin@h DB 01H
__C15F5C06_ammintrin@h DB 01H
__D112916B_mm3dnow@h DB 01H
__897A866B_intrin@h DB 01H
__B952EC38_wchar@h DB 01H
__DDE9EB90_cwchar DB 01H
__9E296EA6_iosfwd DB 01H
__6252065D_initializer_list DB 01H
__D75F4328_concepts DB 01H
__0812AE9F_compare DB 01H
__C60A11A5_utility DB 01H
__0A2ECE85___msvc_iter_core@hpp DB 01H
__53F7AAE2_xutility DB 01H
__425B1DA2_iterator DB 01H
__710F171D_share@h DB 01H
__0E7DBA5B___msvc_system_error_abi@hpp DB 01H
__DA434938_cerrno DB 01H
__67A587F8_corecrt_terminate@h DB 01H
__EE509C34_eh@h DB 01H
__AF00D4CB_vcruntime_exception@h DB 01H
__F8699A58_exception DB 01H
__E9D9B286___msvc_sanitizer_annotate_container@hpp DB 01H
__E19D6A2B___msvc_string_view@hpp DB 01H
__52C0BB20_limits DB 01H
__F5B16096_new DB 01H
__F265168E_xatomic@h DB 01H
__E13FC630_tuple DB 01H
__AC9F7266_xmemory DB 01H
__EDB138D1_xpolymorphic_allocator@h DB 01H
__D84CF4FA_xstring DB 01H
__7127A005_stdexcept DB 01H
__93D6BF98_xcall_once@h DB 01H
__EFD2379E_xerrc@h DB 01H
__5247212B_xatomic_wait@h DB 01H
__ECDD02A1___msvc_threads_core@hpp DB 01H
__417AF502_time@h DB 01H
__81AF4379_ctime DB 01H
__E53349A3_xtimec@h DB 01H
__0162587A_xthreads@h DB 01H
__39F5E7E2_atomic DB 01H
__2C8BADB8_system_error DB 01H
__1EC0281A_vcruntime_typeinfo@h DB 01H
__232859FB_typeinfo DB 01H
__EE6EB7AE_memory DB 01H
__C22BE0A1_xfacet DB 01H
__4E0790C3___msvc_xlocinfo_types@hpp DB 01H
__985C5DFB_ctype@h DB 01H
__48A9DA64_cctype DB 01H
__8D4E1EDC_locale@h DB 01H
__62AB48FF_clocale DB 01H
__3CA1BA33_xlocinfo DB 01H
__077280CB_xlocale DB 01H
__0544CD20_xiosbase DB 01H
__738718B9_streambuf DB 01H
__99F5E6DC_xlocnum DB 01H
__0D7C5A80_ios DB 01H
__E0313BB7___msvc_ostream@hpp DB 01H
__77B26F35_istream DB 01H
__14625A0F_ostream DB 01H
__318ED0FD_iostream DB 01H
__66571700_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXIW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	?Multiply@@YAHHH@Z				; Multiply
PUBLIC	_main
PUBLIC	??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_08EOBDLMOI@Multiply@			; `string'
EXTRN	__imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z:PROC
EXTRN	__imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z:PROC
EXTRN	__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ:PROC
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEHXZ:PROC
EXTRN	?Log@@YAXPBD@Z:PROC				; Log
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT ??_C@_08EOBDLMOI@Multiply@
CONST	SEGMENT
??_C@_08EOBDLMOI@Multiply@ DB 'Multiply', 00H		; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z
_TEXT	SEGMENT
__Ostr$ = 8						; size = 4
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z PROC ; std::endl<char,std::char_traits<char> >, COMDAT
; File C:\YSW\code\v studio\Community\VC\Tools\MSVC\14.50.35717\include\__msvc_ostream.hpp
; Line 1012
	push	ebp
	mov	ebp, esp
	push	esi
	mov	ecx, OFFSET __E0313BB7___msvc_ostream@hpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	esi, DWORD PTR __Ostr$[ebp]
	push	10					; 0000000aH
	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, esi
	call	DWORD PTR __imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z
	movzx	ecx, al
	push	ecx
	mov	ecx, esi
	call	DWORD PTR __imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z
	mov	ecx, esi
	call	DWORD PTR __imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ
	mov	eax, esi
	pop	esi
; Line 1016
	pop	ebp
	ret	0
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ENDP ; std::endl<char,std::char_traits<char> >
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
	mov	ecx, OFFSET __66571700_Math@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	8
	push	5
	call	?Multiply@@YAHHH@Z			; Multiply
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	add	esp, 8
	push	eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
	mov	ecx, DWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	DWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEHXZ
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
; Line 6
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __66571700_Math@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	OFFSET ??_C@_08EOBDLMOI@Multiply@
	call	?Log@@YAXPBD@Z				; Log
	mov	eax, DWORD PTR _a$[ebp]
	add	esp, 4
	imul	eax, DWORD PTR _b$[ebp]
; Line 9
	pop	ebp
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?__empty_global_delete@@YAXPAXIW4align_val_t@std@@@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
___formal$ = 16						; size = 4
?__empty_global_delete@@YAXPAXIW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
	mov	ecx, OFFSET __66571700_Math@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAXIW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?__empty_global_delete@@YAXPAXW4align_val_t@std@@@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
	mov	ecx, OFFSET __66571700_Math@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAXW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
	mov	ecx, OFFSET __66571700_Math@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\24130\Desktop\C++\Project1\Math.cpp
	mov	ecx, OFFSET __66571700_Math@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
